name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create_release
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: Automated Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: This is an automated release for ${{ github.ref }}.
        env:
          GITHUB_TOKEN: ${{ github.token }}
  
  linux_amd64:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt update && sudo apt install -y libjack-dev libasound2-dev
      - run: cmake -B rtmidi/build rtmidi && cmake --build rtmidi/build && cmake -B build && cmake --build build
      - run: cd build && zip -r beatstep-linux_amd64.zip beatstep
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/beatstep-linux_amd64.zip
          asset_name: beatstep-linux_amd64.zip
          asset_content_type: application/zip

  # windows_amd64:
  #   runs-on: windows-latest
  #   needs: create_release
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #     - run: cmake -B rtmidi/build rtmidi && cmake --build rtmidi/build && cmake -B build && cmake --build build
  #     - run: cd build && zip -r beatstep-windows_amd64.zip beatstep
  #     - name: upload linux artifact
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}
  #       with:
  #         upload_url: ${{ needs.create_release.outputs.upload_url }}
  #         asset_path: ./build/beatstep-windows_amd64.zip
  #         asset_name: beatstep-windows_amd64.zip
  #         asset_content_type: application/zip

  macos:
    runs-on: macos-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake -B rtmidi/build rtmidi && cmake --build rtmidi/build && cmake -B build && cmake --build build
        env:
          CMAKE_OSX_ARCHITECTURES: arm64;x86_64
      - run: cd build && zip -r beatstep-macos.zip beatstep
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/beatstep-macos.zip
          asset_name: beatstep-macos.zip
          asset_content_type: application/zip
